### ISSUE TITLE
Could not pass event CreatureSpawnEvent to VanillaTweaks v1.3.2-beta

### ISSUE THREAD

**Issue by RisPNG** [teakivy/vanilla-tweaks#2]
Error shown in the console, seems like LargerPhantoms pack is causing this. In terms of the functionality of the plugin, I don't know yet, will update.

**Comment by teakivy** [comment]
Hey, can you paste the entire error? (Should be in <server>/logs) I can't seen to replicate this, thanks!

**Comment by RisPNG** [comment]
https://pastebin.com/2jCt5pbX

This is the latest error I've gotten. Happens at night when phantoms are trying to spawn. They do spawn though.

Weirdly enough, I've not receive this error anymore after a while.

**Comment by teakivy** [comment]
This will be fixed in the next version, thanks!
