### ISSUE TITLE
Joined players instantly go afk

### ISSUE THREAD

**Issue by RisPNG** [teakivy/vanilla-tweaks#4]
Doesn't really bother me but an issue nonetheless. Since I've enabled "display-to-everyone", Players automatically broadcast afk message upon joining if they leave the game and re-join x minutes after.

x refers to the time you set on "afk-after" in config.yml. Mine is 5 minutes.

Replicate: Join the server, leave the server, wait 5 minutes, and re-join.

[Image](https://i.imgur.com/MGGR9ju.png)

**Comment by teakivy** [comment]
Should be fixed in the next version (finalizing 1.4.0-beta now)

**Comment by teakivy** [comment]
Just published [v1.4.0-beta](https://github.com/teakivy/vanilla-tweaks/releases/tag/1.4.0-beta)!

**Comment by RisPNG** [comment]
Awesome!
