### ISSUE TITLE
sneak-to-bottle-all not consuming correct XP points

### ISSUE THREAD

**Issue by RisPNG** [teakivy/vanilla-tweaks#5]
As per title, when sneaking to bottle all it only takes the amount set on "take-xp-amount: x".

To replicate:
I have my "take-xp-amount" set to 22. (if it matters)
I have 64 bottles and I sneak to bottle all, I'll get 64 XP bottles but it only consumes 22 XP points.

**Comment by teakivy** [comment]
Fixed in Hotfix v1.4.1 (should be released within an hour)

**Comment by teakivy** [comment]
Just published [v1.4.1-beta](https://github.com/teakivy/vanilla-tweaks/releases/tag/1.4.1-beta) that fixes this, as well as adds your 
auto /ch toggle suggestion :D

**Comment by RisPNG** [comment]
Thanks!
